name: driver_app
description: "A new E4ProTech project."
publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: ^3.10.4

dependencies:
  firebase_core: ^3.15.2
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2
  dio: ^5.9.0
  device_info_plus: ^12.3.0
  flutter_local_notifications: ^19.5.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/taxy.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/images/taxy.png
  android: true
  ios: true
